// Generated by scripts/generate-map.mjs — do not edit by hand.
export const MAP_WIDTH = 198;
export const MAP_HEIGHT = 100;
export const MAP_REGION = {"lat":{"min":-56,"max":71},"lng":{"min":-168,"max":168}} as const;
