// Pre-renders the dotted world map to static SVGs and emits the projection
// metadata the client needs. Keeps `dotted-map` (and its country geometry)
// out of the browser bundle entirely.
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import DottedMap from "dotted-map";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const map = new DottedMap({ height: 100, grid: "diagonal" });
const { region, width, height } = map.image;

const variants = {
  light: { color: "#00000040" },
  dark: { color: "#FFFFFF40" },
};

mkdirSync(join(root, "public"), { recursive: true });
for (const [name, { color }] of Object.entries(variants)) {
  const svg = map
    .getSVG({
      radius: 0.22,
      color,
      shape: "circle",
      backgroundColor: "transparent",
    })
    // Coordinates come out at full float precision ("10.392304845413264").
    // Two decimals is well under a pixel at any realistic render size and
    // cuts the file by roughly two thirds.
    .replace(/(\d+\.\d{3,})/g, (n) => String(Math.round(n * 100) / 100))
    .replace(/\n\s*/g, "");
  writeFileSync(join(root, `public/world-map-${name}.svg`), svg);
}

// The default projection is Mercator over a clipped region, so the client
// must not assume a full -180..180 / -90..90 equirectangular grid.
writeFileSync(
  join(root, "components/ui/map.projection.ts"),
  `// Generated by scripts/generate-map.mjs — do not edit by hand.
export const MAP_WIDTH = ${width};
export const MAP_HEIGHT = ${height};
export const MAP_REGION = ${JSON.stringify(region)} as const;
`,
);

console.log(`Generated ${width}x${height} map, region`, region);
